# fly.toml app configuration file generated for reddit-dashboard-purple-hill-3043 on 2025-03-04T04:31:32+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reddit-dashboard-purple-hill-3043'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[env]
  FLASK_APP = 'app.py'
  FLASK_ENV = 'production'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
